### PR TITLE
Add *_padded_size_static rounding up to alignment and as_padded_* with recursive padding

### PR DESCRIPTION
**Pull request by superdump**
For interoperability with wgsl.

This seems to work for #29 but I am not certain.

### CODE REVIEW

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
So this change actually isn't right. Structs must _always_ be rounded up to their alignment, not just in a specific situation.

**Comment by superdump** [comment]
This is now based on top of #27 as it uses its `Padded` infrastructure. I have added `as_padded_std140()` and  `as_padded_std430()` which recursively build using the padded types. I'll continue the discussion in #29 as most of the information is over there.

What I think remains to be done:, aside from verifying that this produces correct results for AsStd140/AsStd430 derivation and whatnot, is:
* verify this is correct
* add tests
* As this is no longer just std140 and std430, perhaps it should have another name than 'padded std140' etc? The motivation for me doing this is for WGSL usage.
* add `Writer` support that calls `.as_padded_std140()` instead of `.as_std140()` to ensure padding is added at the end of structs and arrays before the next member

**Comment by cwfitzgerald** [comment]
There shouldn't be a need to have a separate kind of thing. The rules I explained in #29 apply to both std140 and std430, so this should just be the default.

**Comment by superdump** [comment]
Making this the default in a clean way seems to be quite challenging... :/

**Comment by LPGhatguy** [comment]
Hey, I ended up reworking a big chunk of the library to solve this same issue. It should now be compatible with WebGPU/WGSL layout as well as GLSL.

Take a look, if you're still using Crevice!

I'm going to close this PR as it's fallen pretty far behind. We can revisit this idea if it's something that's important on top of the main branch.

**Pull request closed without merging**
